# Generated by Django 3.0.4 on 2020-12-09 14:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_vacancy', '0003_add_Appnull'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='employee_count',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='company',
            name='location',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='salary_max',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='salary_min',
            field=models.PositiveIntegerField(),
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('surname', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=50)),
                ('salary', models.PositiveIntegerField()),
                ('grade', models.CharField(max_length=50)),
                ('education', models.TextField()),
                ('experience', models.TextField()),
                ('portfolio', models.URLField()),
                ('specialty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resumes',
                                                to='app_vacancy.Specialty')),
                ('user',
                 models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resumes',
                                      to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
